[dev]
  framework = "#static"

[build]
  command = "echo No build for this site, we are living on the edge"
  publish = "public"

[context.production]
  environment = { MY_IMPORTANT_VARIABLE = "this is a very important secret" }

# The URL for each edge function

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/rewrite"
  function = "rewrite"




